<?php
/**
 * Copyright (c) new frontiers Software GmbH
 */

namespace NewFrontiers\Breeze;


class EntityAspect
{

    const ADDED = 'Added';
    const MODIFIED = 'Modified';
    const DELETED = 'Deleted';


    public $entityTypeName;

    public $defaultResourceName;

    public $entityState;

    public $originalValuesMap;

    public $autoGeneratedKey;

}