<?php
/**
 * Copyright (c) new frontiers Software GmbH
 */

namespace NewFrontiers\Breeze;


class StructuralType
{

    public $shortName;

    public $namespace;

    public $isComplexType = false;

    public $dataProperties = [];

    public $autoGeneratedKeyType;

    public $defaultResourceName;

    public function addDataProperty() {
        $result = new DataProperty();
        $this->dataProperties[] = $result;
        return $result;
    }

}